version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: namhyong/langchain:latest
    container_name: langchain
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=54.181.1.215
      - REDIS_PORT=6379
    command: >
      sh -c "uvicorn server:app --host 0.0.0.0 --port 8080"
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
